[package]
name = "swanky-polynomial"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
# my_dependency.workspace = true
